"""Generate C++ headers for the REMv2 web UI assets.

The boat has no internet access, so the ESP32 has to serve the whole front-end
itself. The files in src/frontend are therefore converted into PROGMEM string
constants that the firmware can stream straight out of flash (no CDN, no file
system, no extra RAM).

The script runs automatically before every PlatformIO build (see `extra_scripts`
in platformio.ini) and can also be started by hand:

    python scripts/generate_web_assets.py
"""

import os

try:
    Import("env")  # noqa: F821 - injected by SCons when run as a PlatformIO extra script
except NameError:
    env = None


def project_dir():
    """Root of the project.

    SCons does not define __file__ for extra scripts, so ask PlatformIO first and
    only fall back to the script location / working directory when run by hand.
    """
    if env is not None:
        return env.subst("$PROJECT_DIR")
    if "__file__" in globals():
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.getcwd()


PROJECT_DIR = project_dir()

# (source of truth) -> (generated header, C++ symbol)
ASSETS = [
    ("src/frontend/style.css", "src/frontend/assets/styleCss.hh", "STYLE_CSS"),
]

# Delimiter of the C++ raw string literal used for the asset payload.
RAW_DELIMITER = "REMv2Asset"

HEADER = """\
// Auto-generated by scripts/generate_web_assets.py - DO NOT EDIT THIS FILE.
// Source of truth: {source}
// Regenerated on every build by the PlatformIO pre-script.
#pragma once

#include <pgmspace.h>

static const char {symbol}[] PROGMEM = R"{delimiter}({payload}){delimiter}";
"""


def generate(source_relative, header_relative, symbol):
    source = os.path.join(PROJECT_DIR, source_relative)
    header = os.path.join(PROJECT_DIR, header_relative)

    if not os.path.isfile(source):
        raise SystemExit("generate_web_assets: missing asset " + source_relative)

    # universal newlines on read, LF on write -> stable output on every platform
    with open(source, "r", encoding="utf-8") as handle:
        payload = handle.read()

    terminator = ")" + RAW_DELIMITER + '"'
    if terminator in payload:
        raise SystemExit(
            "generate_web_assets: " + source_relative + " contains the C++ raw string terminator " + terminator
        )

    content = HEADER.format(
        source=source_relative.replace("\\", "/"),
        symbol=symbol,
        delimiter=RAW_DELIMITER,
        payload=payload,
    )

    if os.path.isfile(header):
        with open(header, "r", encoding="utf-8") as handle:
            if handle.read() == content:
                print("generate_web_assets: " + header_relative + " is up to date")
                return

    directory = os.path.dirname(header)
    if directory and not os.path.isdir(directory):
        os.makedirs(directory)

    with open(header, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)

    print("generate_web_assets: wrote " + header_relative + " (" + str(len(payload)) + " B of " + source_relative + ")")


def main():
    for source_relative, header_relative, symbol in ASSETS:
        generate(source_relative, header_relative, symbol)


main()
